# Generated by Django 2.0 on 2017-12-02 17:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('pie', '0001_initial'),
        ('pie_run', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieRunOrder',
            fields=[
                ('pie_run_order_id',
                 models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('pie_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pie_run.PieRun')),
            ],
        ),
        migrations.CreateModel(
            name='PieRunOrderEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pie.Pie')),
                ('pie_run_order',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pie_run_order.PieRunOrder')),
            ],
        ),
    ]
