# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pie', '0004_auto_20171118_1103'),
        ('pie_run', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieRunOrder',
            fields=[
                ('pie_run_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('pie_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pie_run.PieRun')),
            ],
        ),
        migrations.CreateModel(
            name='PieRunOrderEntries',
            fields=[
                ('pie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pie.Pie')),
                ('quantity', models.IntegerField()),
                ('pie_run_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pie_run_order.PieRunOrder')),
            ],
        ),
    ]
