# Generated by Django 2.0 on 2018-03-20 20:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pie_run_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pierunorderentry',
            name='id',
        ),
        migrations.AddField(
            model_name='pierunorderentry',
            name='pie_run_order_entry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
