# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pie_run_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PieRunOrderEntries',
            new_name='PieRunOrderEntry',
        ),
    ]
