# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieRun',
            fields=[
                ('pie_run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PieRunOrder',
            fields=[
                ('pie_run_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('pie_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pie.PieRun')),
            ],
        ),
        migrations.CreateModel(
            name='PieRunOrderEntries',
            fields=[
                ('pie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pie.Pie')),
                ('quantity', models.IntegerField()),
                ('pie_run_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pie.PieRunOrder')),
            ],
        ),
        migrations.RemoveField(
            model_name='pie',
            name='id',
        ),
        migrations.AddField(
            model_name='pie',
            name='pie_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
