# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0003_auto_20171117_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pierunorder',
            name='pie_run',
        ),
        migrations.RemoveField(
            model_name='pierunorderentries',
            name='pie',
        ),
        migrations.RemoveField(
            model_name='pierunorderentries',
            name='pie_run_order',
        ),
        migrations.DeleteModel(
            name='PieRun',
        ),
        migrations.DeleteModel(
            name='PieRunOrder',
        ),
        migrations.DeleteModel(
            name='PieRunOrderEntries',
        ),
    ]
